# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('HatchBack', 'HatchBack'), ('Seden', 'Seden'), ('SUV', 'SUV'), ('MUV', 'MUV')], max_length=30)),
                ('fuel', models.CharField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL')], max_length=30)),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbrand', to='testapp.CarBrands')),
            ],
        ),
    ]
