# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_spareparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='airbags',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='brakes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='clutchplates',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='headlamps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='spoiler',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='taillamps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='wheels',
            field=models.IntegerField(null=True),
        ),
    ]
