# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190516_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='spoiler',
            field=models.IntegerField(blank=True),
        ),
    ]
