# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190516_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='airbags',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='brakes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='clutchplates',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='headlamps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='taillamps',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='wheels',
            field=models.IntegerField(blank=True),
        ),
    ]
